
modLoader = "javafml"
loaderVersion = "[46,)"
issueTrackerURL = "https://github.com/f-raZ0R/exclusionslib/issues"
license = "CC-BY-4.0"

[[mods]]
modId = "exclusions_lib"
version = "1.0.2"
displayName = "Exclusions Lib"
# updateJSONURL=""
displayURL = "https://github.com/f-raZ0R/exclusionslib"
logoFile = "icon.png"
logoBlur = false
authors = "Athebyne"
description = "A library for Excluding Things from other Things."


[[dependencies.exclusions_lib]]
modId = "forge"
mandatory = true
versionRange = "[46,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.exclusions_lib]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"


